spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

sa-token:
  token-name: Mayo-Access-Token
  timeout: 43200
  token-style: simple-uuid
  is-log: false
  is-print: false
